name: Bug Report
description: File a bug report
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: xStage version
      placeholder: "0.1.0"
    validations:
      required: true
  
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "AlmaLinux 9"
    validations:
      required: true